apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.2.5
    helm:
      parameters:
        - name: controller.kind
          value: 'DaemonSet'
        - name: controller.metrics.enabled
          value: 'true'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: nginx-ingress
    server: "https://kubernetes.default.svc"
