apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.37.3
    helm:
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: ingress.ingressClassName
          value: 'nginx'
        - name: ingress.hosts[0]
          value: 'grafana.{{ .Values.domain }}'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: monitoringv2
    server: "https://kubernetes.default.svc"
