apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bhav
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/hajdukd/bhav-sample-infra.git
    targetRevision: main
    path: manifests/productionX/bhav
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: bhav
    server: "https://kubernetes.default.svc"
